name: Compile Apps for Me

on: 
  workflow_dispatch:
    inputs:
      app:
        description: 'App to compile'
        required: true
        default: 'ladybird'
        type: choice
        options:
        - ladybird

jobs:
  ladybird:
    runs-on: ubuntu-latest
    if: github.event.inputs.app == 'ladybird'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    # Uncomment to upload the package as an artifact
    - name: Upload Package Archive
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
